import Head from "next/head";
import Header from "../components/Header";
import Awards from "../sections/Awards";
import Hero from "../sections/Hero";
import Podiums from "../sections/Podiums";
import Ranking from "../sections/Ranking";
import s from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Benjamin Insfran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <Header />
        <Hero />
        <Ranking />
        <Podiums />
        <Awards />
      </main>
    </div>
  );
}
