import Head from "next/head";
import Articles from "../sections/Articles";
import Awards from "../sections/Awards";
import NextSteps from "../sections/NextSteps";
import Hero from "../sections/Hero";
import Podiums from "../sections/Podiums";
import Ranking from "../sections/Ranking";
import OG from "../sections/About/OG";

export default function Home() {
  return (
    <>
      <Head>
        <title>Benjamin Insfran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Hero />
        <Ranking />
        <Podiums />
        <Awards />
        <OG />
        <Articles />
        {/* <Contribution /> */}
        <NextSteps />
      </main>
    </>
  );
}
